name: lint,test,deploy
on: push
jobs:
  lint_test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm test  
      - name: deploy
        run: echo "i am deploying"
      
